version: "3.7"
services:
  bf1942:
    image: bf42:latest
    ports:
      - 14567:14567/udp # Server
      - 14667:14667/tcp # BFSM
      - 22000:22000/udp # Gamespy LAN
      - 23000:23000/udp # Gamespy
    volumes:
      - ./settings:/bf1942/mods/bf1942/settings/
    environment:
      BFSM: "yes"
